spring:
  application:
    name: JR-final
  datasource:
    url: jdbc:postgresql://localhost:5432/JR-final
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yml
      enabled: true
  jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: none

server:
  servlet:
    context-path: /

logging:
  level:
    liquibase: info