spring:
  config:
    import: env.properties
  application:
    name: JR-final
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yml
      enabled: true
  jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: none

server:
  servlet:
    context-path: /

token:
  signing:
    key: ${JWT_KEY}

logging:
  level:
    liquibase: info