--liquibase formatted sql

-- changeset author:01-init-db
CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(128) NOT NULL,
    email    VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL
);
CREATE UNIQUE INDEX users_email_uindex ON users (email);


CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS ticker
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    company_name VARCHAR(128) NOT NULL
);
CREATE UNIQUE INDEX ticker_name_uindex ON users (name);


CREATE TABLE IF NOT EXISTS ticker_data
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date      DATE    NOT NULL,
    open      INTEGER,
    close     INTEGER,
    high      INTEGER,
    low       INTEGER,
    user_id   INTEGER NOT NULL,
    ticker_id INTEGER NOT NULL,
    CONSTRAINT user_date_idx UNIQUE (user_id, date),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (ticker_id) REFERENCES ticker (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX ticker_data_unique_user_ticker ON ticker_data (user_id, ticker_id);